# This file is adapted from coraza-proxy-wasm/ftw/docker-compose.yml
# Original work: Copyright 2022 The OWASP Coraza contributors
# Adapted for coraza-rs dynamic module implementation

services:
  albedo:
    image: ghcr.io/coreruleset/albedo:0.2.0
  chown:
    image: alpine:3.16
    command:
      - /bin/sh
      - -c
      # Early creates the log file so coraza-logs does not fail even if envoy is not yet healthy
      - touch /home/envoy/logs/envoy.log && chown -R 101:101 /home/envoy/logs
    volumes:
      - ./logs:/home/envoy/logs:rw
  envoy:
    depends_on:
      - chown
      - albedo
    image: ${ENVOY_IMAGE:-envoy-with-coraza-module:latest}
    command:
      - -c
      - ${ENVOY_CONFIG:-/conf/envoy-config.yaml}
      - --log-level
      - debug
      - --component-log-level
      - http:debug
      - --log-format [%Y-%m-%d %T.%f][%t][%l][%n] [%g:%#] %v
      - --log-path
      - /home/envoy/logs/envoy.log
    volumes:
      - .:/conf
      - ./logs:/home/envoy/logs:rw
      - build:/build
    environment:
      - ENVOY_DYNAMIC_MODULES_SEARCH_PATH=/usr/local/lib
    ports:
      - 8080:80
  coraza-logs:
    depends_on:
      - envoy
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - tail -F /home/envoy/logs/envoy.log 2>/dev/null | grep --line-buffered "Coraza:" >> /home/envoy/logs/ftw.log
    volumes:
      - ./logs:/home/envoy/logs:rw
  envoy-logs:
    depends_on:
      - envoy
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - tail -c +0 -f /home/envoy/logs/envoy.log > /build/ftw-envoy.log
    volumes:
      - ./logs:/home/envoy/logs:ro
      - build:/build
  ftw:
    depends_on:
      - envoy-logs
      - coraza-logs
    build: .
    environment:
      - FTW_ARGS
      - FTW_OUTPUT_PATH
    volumes:
      - ./logs:/home/envoy/logs:ro
      - build:/build
      - .:/workspace-output:rw
  ftw-memstats:
    depends_on:
      - ftw
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - "tail -c +0 -f /home/envoy/logs/envoy.log | grep 'Sys: '"
    volumes:
      - ./logs:/home/envoy/logs:ro
volumes:
  build:
